plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: |
        set -euxo pipefail
        mvn -B versions:set -DnewVersion=${nextRelease.version}
        echo "NEXT_VERSION=${nextRelease.version}" >> build.env
        
        mvn -B -DskipTests package
        
        mvn -Pnative package -DskipTests
  - - "@semantic-release/github"
    - assets:
        - path: "target/patches.jar"
          label: "JAR (v${nextRelease.version})"
        - path: "target/patches"
          label: "Native image (v${nextRelease.version})"
  - - "@semantic-release/git"
    - assets:
        - pom.xml
      message: "chore(release): bump ${nextRelease.version}"

branches:
  - name: "main"
    prerelease: false
  - name: feature/*
    prerelease: '${name.replace(/^feature\//g, "feat-")}'
  - name: fix/*
    prerelease: '${name.replace(/^fix\//g, "fix-")}'
