name: Build project
on: push

env:
  JAVA_VERSION: '17'
  JAVA_DISTRO: 'zulu'

permissions:
  packages: write
  contents: write

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v4
      - name: Setup java 17
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
      - name: Build project
        run: mvn -B clean package -DskipTests
