name: Release project
on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  maven-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v4
      - name: Setup java 17
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Deploy maven project
        run: mvn -B deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ github.token }}
